### ISSUE TITLE
GPIO range in Kconfig.protobuild may be incorrect

### ISSUE THREAD

**Issue by climategadgets** [DavidAntliff/esp32-ds18b20-example#17]
Several sources list GPIO 34-39 as input only, whereas `Kconfig.protobuild` lists the range as `0 34`, and help text says "GPIOs 35-39 are input-only".

**Comment by DavidAntliff** [comment]
Yes, good catch, thank you: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/gpio.html - the help text should say "34-39" and the range should be `0 33`. I'll fix this.

**Comment by DavidAntliff** [comment]
This will be fixed as part of https://github.com/DavidAntliff/esp32-ds18b20-example/pull/18
